---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: "en"
dictionaryDefinitions:
  - name: project-words
    path: './.cspell.project-words.txt'
    addWords: true
dictionaries: ["project-words"]
ignorePaths:
  - './.cspell.project-words.txt'
  - '**/vscode-extension/**'
  - '**/.git/**'
  - '**/target/**'
  - '.vscode'
